version: "3.9"

networks:
  SP_DEV:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    depends_on:
      - redis

    restart: on-failure
    networks:
      - SP_DEV

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - mysql 

    restart: on-failure
    networks:
      - SP_DEV


  redis:
    image: redis:7.0.8
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - SP_DEV

  mysql:
    image: mysql/mysql-server:8.0 
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=PassWorD
      - MY_SQL_HOST=0.0.0.0
      - MYSQL_DATABASE=snappfood
      - MYSQL_USER=snappfood
      - MYSQL_PASSWORD=PassWorD

    depends_on:
      - redis
    networks:
      - SP_DEV